name: Publish Artifact

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required if publishing to GitHub Packages

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish Artifact
        run: ./gradlew :lib:publish
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For GitHub Packages
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }} # For Central Portal
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}       # For Central Portal
          SIGNING_SECRET_KEYRING_FILE_B64: ${{ secrets.SIGNING_SECRET_KEYRING_FILE_B64 }} # For Central Portal signing
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}         
